//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowAvatarBot {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RainbowAvatarBot.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        internal static string InvalidFlagName {
            get {
                return ResourceManager.GetString("InvalidFlagName", resourceCulture);
            }
        }
        
        internal static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        internal static string UserProfilePictureNotFound {
            get {
                return ResourceManager.GetString("UserProfilePictureNotFound", resourceCulture);
            }
        }
        
        internal static string RepliedUserProfilePictureNotFound {
            get {
                return ResourceManager.GetString("RepliedUserProfilePictureNotFound", resourceCulture);
            }
        }
        
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        internal static string SettingsSentToChat {
            get {
                return ResourceManager.GetString("SettingsSentToChat", resourceCulture);
            }
        }
        
        internal static string SelectFlag {
            get {
                return ResourceManager.GetString("SelectFlag", resourceCulture);
            }
        }
        
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        internal static string UnableToSend {
            get {
                return ResourceManager.GetString("UnableToSend", resourceCulture);
            }
        }
        
        internal static string Agender {
            get {
                return ResourceManager.GetString("Agender", resourceCulture);
            }
        }
        
        internal static string Asexual {
            get {
                return ResourceManager.GetString("Asexual", resourceCulture);
            }
        }
        
        internal static string Bigender {
            get {
                return ResourceManager.GetString("Bigender", resourceCulture);
            }
        }
        
        internal static string Bisexual {
            get {
                return ResourceManager.GetString("Bisexual", resourceCulture);
            }
        }
        
        internal static string Genderfluid {
            get {
                return ResourceManager.GetString("Genderfluid", resourceCulture);
            }
        }
        
        internal static string Genderqueer {
            get {
                return ResourceManager.GetString("Genderqueer", resourceCulture);
            }
        }
        
        internal static string Lesbian {
            get {
                return ResourceManager.GetString("Lesbian", resourceCulture);
            }
        }
        
        internal static string LGBT {
            get {
                return ResourceManager.GetString("LGBT", resourceCulture);
            }
        }
        
        internal static string Nonbinary {
            get {
                return ResourceManager.GetString("Nonbinary", resourceCulture);
            }
        }
        
        internal static string Pansexual {
            get {
                return ResourceManager.GetString("Pansexual", resourceCulture);
            }
        }
        
        internal static string Polysexual {
            get {
                return ResourceManager.GetString("Polysexual", resourceCulture);
            }
        }
        
        internal static string Transgender {
            get {
                return ResourceManager.GetString("Transgender", resourceCulture);
            }
        }
    }
}
