//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowAvatarBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RainbowAvatarBot.locales.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agender.
        /// </summary>
        public static string Agender {
            get {
                return ResourceManager.GetString("Agender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asexual.
        /// </summary>
        public static string Asexual {
            get {
                return ResourceManager.GetString("Asexual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bigender.
        /// </summary>
        public static string Bigender {
            get {
                return ResourceManager.GetString("Bigender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisexual.
        /// </summary>
        public static string Bisexual {
            get {
                return ResourceManager.GetString("Bisexual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed!.
        /// </summary>
        public static string ChangedSuccessfully {
            get {
                return ResourceManager.GetString("ChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occured! Please try again or contact developer..
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genderfluid.
        /// </summary>
        public static string Genderfluid {
            get {
                return ResourceManager.GetString("Genderfluid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genderqueer.
        /// </summary>
        public static string Genderqueer {
            get {
                return ResourceManager.GetString("Genderqueer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name of the flag!.
        /// </summary>
        public static string InvalidFlagName {
            get {
                return ResourceManager.GetString("InvalidFlagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LGBT.
        /// </summary>
        public static string LGBT {
            get {
                return ResourceManager.GetString("LGBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonbinary.
        /// </summary>
        public static string Nonbinary {
            get {
                return ResourceManager.GetString("Nonbinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pansexual.
        /// </summary>
        public static string Pansexual {
            get {
                return ResourceManager.GetString("Pansexual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polysexual.
        /// </summary>
        public static string Polysexual {
            get {
                return ResourceManager.GetString("Polysexual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t find profile picture of profile from the reply! Usually that is because of privacy settings, or user may not have avatar at all..
        /// </summary>
        public static string RepliedUserProfilePictureNotFound {
            get {
                return ResourceManager.GetString("RepliedUserProfilePictureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select flag:.
        /// </summary>
        public static string SelectFlag {
            get {
                return ResourceManager.GetString("SelectFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings command should be sent to my PM..
        /// </summary>
        public static string SettingsSentToChat {
            get {
                return ResourceManager.GetString("SettingsSentToChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Welcome to the @RainbowAvatarBot\! 🏳️‍🌈*
        ///Send me any image/sticker, and I will colorize it\!
        ///
        ///*Available commands*:
        ///  /settings \- change flag
        ///  /avatar \- overlay your avatar with a flag
        ///
        ///*To use bot in groups*:
        ///  Reply to the message with image/sticker with `/colorize` command \(the same works with `/avatar`\) or send image with caption with that command\.
        ///
        ///_Developer of the bot \- @Vital\_7, I am always open to your messages_ :\).
        /// </summary>
        public static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transgender.
        /// </summary>
        public static string Transgender {
            get {
                return ResourceManager.GetString("Transgender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was unable to send the result! Please try again or contact developer..
        /// </summary>
        public static string UnableToSend {
            get {
                return ResourceManager.GetString("UnableToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command!.
        /// </summary>
        public static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t find your profile picture! Please set it or change your privacy settings, so I would be able to see it..
        /// </summary>
        public static string UserProfilePictureNotFound {
            get {
                return ResourceManager.GetString("UserProfilePictureNotFound", resourceCulture);
            }
        }
    }
}
